# Generated by Django 3.2 on 2021-04-13 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGalleryApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='aimage',
            new_name='Image',
        ),
    ]
