# Generated by Django 3.2 on 2021-04-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myGalleryApp', '0002_rename_aimage_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Image',
            new_name='Boom',
        ),
    ]
